create table todos (
  id bigint generated by default as identity primary key,
  text text not null,
  completed boolean default false,
  created_at timestamptz default now()
);

alter table todos enable row level security;

create policy "Todos are publicly readable"
on todos
for select
to anon
using (true);

create policy "Todos can be created publicly"
on todos
for insert
to anon
with check (true);

create policy "Todos can be updated publicly"
on todos
for update
to anon
using (true)
with check (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'todos'
  ) then
    alter publication supabase_realtime add table public.todos;
  end if;
end $$;
